import type { Metadata } from "next";
import { newsreader, poppins } from "./lib/fonts";
import "./index.css";
import Header from "./components/Header";
import ThemeProviders from "./providers/ThemeProviders";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="tr"
      className={`${poppins.variable} ${newsreader.variable}`}
      suppressHydrationWarning
    >
      <body className={`${newsreader.className}`}>
        <ThemeProviders>
          <Header />
          <main className="pt-16">
            {children}
          </main>
        </ThemeProviders>
      </body>
    </html>
  );
}
